services:
  backend:
    build: ./backend
    depends_on:
      - redis
    ports:
      - "9000:9000"
    environment:
      - REDIS_DNS=redis

  frontend:
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=backend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  redis_data:
