name: CD pipeline

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Download repo 
        uses: actions/checkout@v4

        # Takes the cubeconfig secret and decodes it, and then puts it into a file called kubeconfig.
      - name: Creates kubeconfig file
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      # Uses the kubeconfig file to deploy the Kubernetes manifests to the cluster.
      - name: Deploy Cluster
        run: kubectl --kubeconfig kubeconfig apply -f kubernetes/

        
      



      
      
