name: CD pipeline

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: Deploy application
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: bash deploy.sh

      - name: Test application
        run: bash test.sh
