name: CD pipeline

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Download repo 
        uses: actions/checkout@v4

        # Takes the cubeconfig secret and decodes it, and then puts it into a file called kubeconfig.
      - name: Creates kubeconfig file
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      # Uses the kubeconfig file to deploy the Kubernetes manifests to the cluster.
      - name: Deploy development
        if: github.ref_name == 'develop'
        run: kubectl --kubeconfig kubeconfig apply -f kubernetes/development/

      - name: Deploy staging
        if: github.ref_name == 'staging'
        run: kubectl --kubeconfig kubeconfig apply -f kubernetes/staging/

      - name: Deploy production
        if: github.ref_name == 'main'
        run: kubectl --kubeconfig kubeconfig apply -f kubernetes/production/

        
      



      
      
