name: CI pipeline
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: clone down repository
        uses: actions/checkout@v4
      - name: download Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: build backend
        run: go build
        working-directory: backend
      - name: build frontend 
        run: go build
        working-directory: frontend
      - name: testing
        run: go test
        working-directory: frontend

      #GHCR --- Container registry
      - name: Login to GHCR
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend image
        if: github.event_name == 'push'
        run: docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./backend

      - name: Build frontend image
        if: github.event_name == 'push'
        run: docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest ./frontend

      - name: Push backend image
        if: github.event_name == 'push'
        run: docker push ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Push frontend image
        if: github.event_name == 'push'
        run: docker push ghcr.io/${{ github.repository_owner }}/frontend:latest
        
